### PR TITLE
FFmpeg configuration updates fixing Windows build

### PR DESCRIPTION
**Pull request by meepzh**
### Summarize your change.

This builds upon the work that Mark did to improve the configuration options for FFmpeg in #360 with Mark's [blessing](https://github.com/markreidvfx/OpenRV/pull/1#issuecomment-1925480414)!

### Describe the reason for the change.

This fixes use of `PKG_CONFIG_PATH`, `RV_FFMPEG_COMMON_CONFIG_OPTIONS`, `RV_FFMPEG_PATCH_COMMAND_STEP` (https://github.com/AcademySoftwareFoundation/OpenRV/issues/15#issuecomment-1848415212), and other Windows-specific build issues such as https://github.com/AcademySoftwareFoundation/OpenRV/discussions/67#discussioncomment-8122471.

### Describe what you have tested and on which operating system.

This has been tested on Arch Linux 6.6.8 and Windows 10.0.22631, running the same test from [here](https://github.com/AcademySoftwareFoundation/OpenRV/pull/360#issuecomment-1907411330).

### Add a list of changes, and note any that might need special attention during the review.

Specific details can be found [here](https://github.com/AcademySoftwareFoundation/OpenRV/pull/360#issuecomment-1907411330). I did not include the change to apply `SEPARATE_ARGUMENTS` to `RV_FFMPEG_CONFIG_OPTIONS`, since `RV_FFMPEG_CONFIG_OPTIONS` did not seem applicable given the [CMake documentation](https://cmake.org/cmake/help/latest/command/separate_arguments.html), but I can include that change as well.

### If possible, provide screenshots.

https://github.com/AcademySoftwareFoundation/OpenRV/pull/360#issuecomment-1907411330

Thanks!

### CODE REVIEW

**Comment by garrett-wbpa** [comment]
Chiming in to say that this patch fixed an [openssl issue](https://github.com/AcademySoftwareFoundation/OpenRV/discussions/91#discussioncomment-8376384) I was having with RV_DEPS_FFMPEG. Thanks for finding it!

**Comment by cedrik-fuoco-adsk** [comment]
Thanks for the contribution @meepzh!

I encountered myself, and I came up with a similar solution. The difference is that I don't have that loop that you didn't like.

I'd like to propose a change for that loop. Do you have the time to do an extra commit? @meepzh 
If you don't have time, no problem, I can take over the changes. I'll post another comment about the refactor of the loop.

**Comment by meepzh** [comment]
Thanks Cedrik! Sure, I can add it. I saw the commit you've pinged me in and learned some new things about CMake! I'll await your comment then.

**Comment by cedrik-fuoco-adsk** [comment]
I was hoping to use cmake_path from CMake to convert the paths, but I'm not 100% confident that it works in some edge cases.
You changes are great and fix the issues. I am currently testing your changes on our internal CI. Once they pass, we can accept the PR. @meepzh

**Comment by bernie-laberge** [comment]
This is fantastic @meepzh !

**Review by bernie-laberge — APPROVED** [review]
Thank you so much for the fix !
The fix builds fine on my Mac+Windows and also on our internal CIs on all platforms.
This is great.

**Pull request merged**
