### PR TITLE
Thread.cpp: change ucontext to ucontext_t

### PR DESCRIPTION
**Pull request by adro79**
Fix error when building on Linux (At least on Arch Linux)

Signed-off-by: adro79 <57686179+adro79@users.noreply.github.com>

### CODE REVIEW

**Comment by marcomeyerVFX** [comment]
not only on Arch, this fix is also required on any EL9.1 Distro

**Review by geffrak — APPROVED** [review]

**Comment by geffrak** [comment]
Awesome! It doesn't seem to break anything with RHEL7.

**Review by rogernelson — APPROVED** [review]
Thank you for this. Great to know that RV can be built on other Linux distros.

**Comment by adro79** [comment]
> Thank you for this. Great to know that RV can be built on other Linux distros.

Regarding building on Arch Linux, this is the only fix I was able to provide.
The other errors I found are mentioned in #15 and @marcomeyerVFX seems to have found the fixes.

**Pull request merged**
