### PR TITLE
VFX 2023: Updating Python short version number

### PR DESCRIPTION
**Pull request by tbabiin**
### Linked issues
N/A

### Summarize your change.
Fixing the build since OCIO looks for python3.9

### Describe the reason for the change.
The build is broken

### Describe what you have tested and on which operating system.
Windows, Mac & Linux

### Add a list of changes, and note any that might need special attention during the review.
- Refactoring the code to avoid code duplication and sync'ing the short number with all other version numbers in this file

### If possible, provide screenshots.

### CODE REVIEW

**Comment by tbabiin** [comment]
Note: This is a suggestion on how to fix, we can discuss other ways to remove some duplication or, I can just change the short variable to "3.10". Let me know which idea you like the most.

**Comment by geffrak** [comment]
How does this fixes OCIO?

**Comment by tbabiin** [comment]
> How does this fixes OCIO?

OCIO uses Python for bindings, Python API. We pass the python EXE path and the library (DLL/SO) to the OCIO ExternalPrj_Add build. Those are hint points for OCIO's CMake to "Find Python" (FindPython.cmake). Passing a bad path to a unexisting file will make OCIO fail to configure. Hence, Python39 isn't found hence the fix.

**Comment by geffrak** [comment]
> > How does this fixes OCIO?
> 
> 
> 
> OCIO uses Python for bindings, Python API. We pass the python EXE path and the library (DLL/SO) to the OCIO ExternalPrj_Add build. Those are hint points for OCIO's CMake to "Find Python" (FindPython.cmake). Passing a bad path to a unexisting file will make OCIO fail to configure. Hence, Python39 isn't found hence the fix.

Oh! I missed the remaining 3.9 from the merge of main (and the OCIO feature branch) into the vfx2023 feature branch.

**Review by geffrak — APPROVED** [review]

**Pull request merged**
